services:
  application:
    container_name: application
    build:
      context: ./application
      dockerfile: ../Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./application:/application
      - node_modules:/application/node_modules
    command: ["dev"]

volumes:
  node_modules:
